# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
# epsilon_anneal_time: 500000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "drima_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
dist_N: 10
dist_K: 1
dist_N_env: 8
dist_Np_env: 8
dist_K_env: 8
n_cos: 64
# risk_agent: "neutral"
risk_agent: "seek"
# risk_env: "neutral"
risk_env: "averse"
# risk_env: "seek"

mac: "dist_mac"
agent: "rnn_dist"

name: "qmix"
